### ISSUE TITLE
implement CSV-Parsing logic in Dataset-store

### ISSUE THREAD

**Issue by tk-king** [edge-ml/Dataset-store#2]

**Comment by tk-king** [comment]
- Need to add error-handling in the dataset-store (bad csv-files,...)

**Comment by KtrauM** [comment]
How large is the dataset, so that processing takes too long and fails? In my testings 1 gigabyte dataset with 9 timeseries took 150 seconds to process. The failure can be caused by something else.  But I agree that we should make the processing async, so that user can estimate when the processing will end.

**Comment by tk-king** [comment]
The file is about 500mb.
The error occurs because nginx closes the connection which causes the timeout.
We can increase the timeout limit but when the server is busy, we would need several minutes which I think is too long.
